### ISSUE TITLE
SSM agent entering hibernating mode on Windows Server 2012 and won't recover

### ISSUE THREAD

**Issue by dnlopes** [aws/amazon-ssm-agent#165]
Hi there,

today we updated all our AMIs to use the latest SSM agent (to version **2.3.415.0**). We setup our automated tests and everything is working fine **except in our Windows Server 2012 images**.

I understand this new version requires some specific policies, and I have them in place. 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ssm:GetDocument",
                "ssm:UpdateAssociationStatus",
                "ssm:ListInstanceAssociations",
                "ssm:UpdateInstanceInformation",
                "ssm:GetDeployablePatchSnapshotForInstance",
                "ssm:PutInventory",
                "ssm:PutParameter",
                "ssm:GetParameter",
                "ssm:DeleteParameter",
                "ssm:ListAssociations"
            ],
            "Resource": "*"
        },
    (...) other permissions here (...)
        {
            "Effect": "Allow",
            "Action": [
                "ssmmessages:CreateControlChannel",
                "ssmmessages:CreateDataChannel",
                "ssmmessages:OpenControlChannel",
                "ssmmessages:OpenDataChannel"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetEncryptionConfiguration"
            ],
            "Resource": "*"
        }
    ]
}
```
For Windows Server 2012, I have the following logs in the SSM-agent:

```
2019-01-28 18:15:59 INFO Windows Only: Job object creation on SSM agent successful
2019-01-28 18:16:00 INFO Getting IE proxy configuration for current user: The operation completed successfully.
2019-01-28 18:16:00 INFO Getting WinHTTP proxy default configuration: The operation completed successfully.
2019-01-28 18:16:00 INFO Proxy environment variables:
2019-01-28 18:16:00 INFO http_proxy: 
2019-01-28 18:16:00 INFO https_proxy: 
2019-01-28 18:16:00 INFO no_proxy: 
2019-01-28 18:17:35 INFO Entering SSM Agent hibernate - MissingRegion: could not find region configuration
```
After entering in hibernation mode, the SSM agent does not recover automatically. The above logs are the logs present in the machine right after creating it. Weirdly enough however, I found out that  restarting the SSM agent solves the issue. After that restart, the service is able to boot propely and starts processing SSM documents.

Bear in mind that the exact same policy is being used in other EC2 instances with other AMIs (Windows Server 2016, for instance), and everything is working smoothly there.

Can you help me here?

Thanks,
David Lopes

**Comment by jasonzaws** [comment]
Hi @dnlopes,

Thanks for bringing this to our attention. Could you please provide some repro steps, especially the region and AMI id, so that we can try to get a repro and further diagnose the issue?

Thanks,
Jason

**Comment by dnlopes** [comment]
Hi @jasonzaws,

after some more analyzes, I detected that our Windows Server 2012 ami hadn't the EC2Config installed. So, I was confident that was the issue. I updated our AMI and installed EC2Config there. Unfortunately, the same error persists.

Here is the routing table of the server:

![image](https://user-images.githubusercontent.com/3472594/51971397-f19c4c00-2470-11e9-947c-75bbaa2a68f7.png)

I can access the instance metadata:

![image](https://user-images.githubusercontent.com/3472594/51971554-58ba0080-2471-11e9-8e89-076944f2ed71.png)

but not the windows activation:

![image](https://user-images.githubusercontent.com/3472594/51971784-e3026480-2471-11e9-85fd-2556119cd1ea.png)

As I said earlier, restarting the SSM agent solves the issue and the SSM-agent starts properly (though I can't still access the windows activation).

The AMI in question is a custom one, as for the region, it happens in all I've tried so far: Oregon, Sydney, Tokyo, Ireland.

**Comment by Spjak** [comment]
Did this ever get resolved?
We are facing exactly the same issue.
We manually updated the ssm agent on our existing custom Windows 2012 AMI to version 2.3.542.0 and created a new AMI from this.
When we start new instances using this AMI, the agent goes into the hibernation state and only works if restarted.

**Comment by dnlopes** [comment]
Hi @Spjak, we were able to overcome the issue. What we did was to set the SSM-agent service as auto-start _delayed_ in our windows AMIs. After this change, we didn't hit this issue again.

My suspicions are as follow:

1) the SSM agent starts too soon, and _"some other dependencies"_ of SSM are still booting as well. 
2) SSM enters hibernating mode because it can't boot properly due to the dependencies in step 1) being still booting as well.
3) In theory, the SSM agent should auto-recover from the hibernating mode, but that was not the behavior we were observing.

After setting the service as _delayed_ startup the first time the SSM agent service starts, all its dependencies are already properly started, so the SSM agent never enters the hibernating mode.

As I said, these are only my suspicions, and since we were able to workaround the issue in a decent way, I didn't dig more into this.

Hope this helps.

David

**Comment by Spjak** [comment]
Thanks for the input @dnlopes
I had the same suspicion and ended up doing much the same to work around it.
I set the service to manual start and scheduled a task to start it once the server has been running a few minutes. 
That also seems to work consistently.

**Comment by farhank3389** [comment]
We’re also having the same issue. It’s happening on Windows 2012 and 2008 R2. Restarting the agent fixes the issue. I will set the agent to delayed start on all our instances and report back if it fixes the issue.

My only concern is that sometimes the agent sometimes hibernates during the day when an instance hasn’t just rebooted. The delayed start won’t fix that problem but will have to do for now until there is a proper fix from AWS.

**Comment by hiimtu** [comment]
Hi everyone,

We have identify the bug that is causing this issue. We are releasing a new agent version [2.3.697.0]. Please update and let us know if you are still seeing this issue! Thanks for all your help!

S3 bucket: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgentSetup.exe

**Comment by hiimtu** [comment]
Hello, the team is working on releasing this fix. 

Apologies for the inconveniences.

**Comment by dnlopes** [comment]
> Hello, the team is working on releasing this fix.
> 
> Apologies for the inconveniences.

Hi,

wasn't this supposed to be already fixed in an earlier version?

**Comment by farhank3389** [comment]
@dnlopes We’re still having the connection lost issue on agents which were supposed to be fixed

**Comment by farhank3389** [comment]
Any updates on this? It’s causing a lot of problems with patching etc.

**Comment by shihuazhang** [comment]
@farhank3389 the latest version includes a couple of fixes for the hibernation issue in general. 

Could you please verify if it fixes the issue you been having?
