### ISSUE TITLE
Updating amazon-ssm-agent from 2.3.707.0 to latest caused cannot find the amazon-ssm-agent-windows-amd64.tar.gz information in the Manifest file

### ISSUE THREAD

**Issue by HongChenTW** [aws/amazon-ssm-agent#233]
Hi, we attempted to upgrade ssm agent via `aws:updateSsmAgent` document and encountered a issue:

```
Updating amazon-ssm-agent from 2.3.707.0 to latest
Successfully downloaded https://s3.us-west-2.amazonaws.com/amazon-ssm-us-west-2/ssm-agent-manifest.json
----------ERROR-------
cannot find the amazon-ssm-agent-windows-amd64.tar.gz information in the Manifest file
```

After tracing code, we found that ssm agent only determines whether EC2's OS is Amazon Linux, RedHat, Ubuntu, CentOS, SuseOS, Respbian and WindowsNano container, Debian is not included.

While the else case is Windows, it will lead Debian EC2 to download Windows ssm agent.

https://github.com/aws/amazon-ssm-agent/blob/57ff56294241bacbfcefc33ea878c3ad0d5da2c3/agent/updateutil/updateutil.go#L261-L308

`arch` is correctly determined by `runtime.GOARCH`.

https://github.com/aws/amazon-ssm-agent/blob/57ff56294241bacbfcefc33ea878c3ad0d5da2c3/agent/updateutil/updateutil.go#L318

The package extension is determined to be `tar.gz` since the ssm document run on linux EC2.

https://github.com/aws/amazon-ssm-agent/blob/57ff56294241bacbfcefc33ea878c3ad0d5da2c3/agent/updateutil/updateutil_unix.go#L67

So the final combination of package name is `amazon-ssm-agent-windows-amd64.tar.gz`, which lead to this issue.

**Comment by shihuazhang** [comment]
Thanks for your interest about amazon ssm agent. We’ll work on this bug fix.

**Comment by nickmccally** [comment]
I am experiencing the same issue with several of my servers on debian 8.

**Comment by nickmccally** [comment]
@shihuazhang Any ETA on resolving this, as I am receiving false compliance issue warnings for my machines running ubuntu

**Comment by federicodallari27** [comment]
Hi @shihuazhang any update made so far? Still getting same issue with Oracle Linux 7.
Please send a feedback. Thanks

**Comment by CheyiLin** [comment]
I think this issue has been fixed in 529edef5a635caa1e8e595a0b079fafa705b3821, released as `2.3.871.0`.

**Comment by shihuazhang** [comment]
@CheyiLin Yes, it's been fixed, I forgot to update this thread. 

Thanks

**Comment by jk-tagbangers** [comment]
This issue still occurs on other unsupported Linux distributions.

It is necessary to output an error log as an unsupported OS instead of finally judging it as Windows.
